# Generated by Django 5.2.10 on 2026-01-30 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='Suplemento', max_length=25),
        ),
        migrations.CreateModel(
            name='Variacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributo', models.CharField(default='sabor', max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variaciones', to='store.producto')),
            ],
        ),
    ]
