# Generated by Django 5.2.10 on 2026-01-30 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_producto_categoria_variacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
