# Generated by Django 5.2.10 on 2026-02-04 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.variacion'),
        ),
    ]
