# Generated by Django 5.2.10 on 2026-02-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderitem_variacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='costo_de_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orden',
            name='tipo_de_envio',
            field=models.CharField(default='Retiro en Local', max_length=30),
        ),
    ]
