# Generated by Django 5.2.10 on 2026-03-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_orden_costo_de_envio_orden_tipo_de_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(default='Efectivo', max_length=50),
        ),
    ]
