# Generated by Django 5.2.10 on 2026-03-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orden_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
